version: '3.8'
services:
  payment-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: payment_db
    ports:
      - "3310:3306"
    volumes:
      - payment-data:/var/lib/mysql

  payment-service:
    build: .
    ports:
      - "8084:8084"
    depends_on:
      - payment-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://payment-db:3306/payment_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true

volumes:
  payment-data:
